OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
ALLOW_WARNINGS = yes
OLED_TRANSPORT = i2c

WPM_ENABLE = yes
LTO_ENABLE = yes
# OLED_UPDATE_INTERVAL = 0
# OLED_DISPLAY_CLOCK = 0x24
