OLED_ENABLE = yes
OLED_DRIVER = SSD1306
OLED_FADE_OUT = no
# OLED_FADE_OUT_INTERVAL = 2
# OLED_TIMEOUT = 10000
OLED_UPDATE_PROCESS_LIMIT = 2
OLED_UPDATE_INTERVAL = 0
# OLED_DISPLAY_CLOCK = 0x24

WPM_ENABLE = yes

ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes

CONSOLE_ENABLE = no
LTO_ENABLE = yes
ALLOW_WARNINGS = yes




